# Generated by Django 4.0.3 on 2022-06-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disc_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(default='11111111111', max_length=11),
        ),
    ]
