# Generated by Django 4.0.2 on 2022-03-17 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disc_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('ra', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.IntegerField(max_length=50)),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ini', models.DateField()),
                ('data_fim', models.DateField()),
                ('dominancia', models.FloatField()),
                ('influencia', models.FloatField()),
                ('cautela', models.FloatField()),
                ('estabilidade', models.FloatField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disc_website.aluno')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ManyToManyField(to='disc_website.Turma'),
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.CharField(max_length=30)),
                ('peso', models.FloatField()),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disc_website.pergunta')),
            ],
        ),
        migrations.AddField(
            model_name='pergunta',
            name='teste',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='disc_website.teste'),
            preserve_default=False,
        ),
    ]
