name: Commit automatico

on:
  pull_request:
    types: [labeled, opened, reopened, synchronize]
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo testando se o label foi adicionado...

      - name: merge
        if: contains(github.event.pull_request.labels.*.name, 'aprovado')
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: homolog
          target_branch: main
          github_token: ${{ github.token }}

      - name: dont merge
        if: false == contains(github.event.pull_request.labels.*.name, 'aprovado')
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Label não adicionado.')
